apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: angular-boilerplate
  
spec:
  project: default

  source:
    repoURL: 'https://github.com/faststartup-tools/kube_manifest.git'
    path: manifest/angular-boilerplate
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: angular-boilerplate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true