apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-boilerplate
spec:
  selector:
    matchLabels:
      app: angular-boilerplate
  replicas: 2
  template:
    metadata:
      labels:
        app: angular-boilerplate
    spec:
      containers:
      - name: angular-boilerplate
        image: ghcr.io/faststartup-tools/angular-boilerplate:build-12
        ports:
        - containerPort: 80

      imagePullSecrets:
       - name: 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

