apiVersion: v1
kind: Service
metadata:
  name: angular-boilerplate-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  selector:
    app: angular-boilerplate
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80


