apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-boilerplate
spec:
  selector:
    matchLabels:
      app: nextjs-boilerplate
  replicas: 2
  template:
    metadata:
      labels:
        app: nextjs-boilerplate
    spec:
      containers:
      - name: nextjs-boilerplate
        image: ghcr.io/faststartup-tools/nextjs-boilerplate:build-1
        ports:
        - containerPort: 80

      imagePullSecrets:
       - name: ghcr-secret

